# Generated by Django 3.0.6 on 2020-05-24 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='age',
        ),
    ]
