# Generated by Django 3.0.6 on 2020-05-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_seller_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='age',
            field=models.IntegerField(blank=True, default=12),
            preserve_default=False,
        ),
    ]
