# Generated by Django 3.0.6 on 2020-05-26 03:23

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_seller_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='contact_number',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
    ]
