# Generated by Django 3.0.5 on 2020-05-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_paymentinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinfo',
            name='Product',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
