# Generated by Django 3.0.5 on 2020-05-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200508_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
