# Generated by Django 3.0.5 on 2020-05-08 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20200508_0643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='colors',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sizes',
            new_name='size',
        ),
    ]
