# Generated by Django 3.0.5 on 2020-05-09 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20200509_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_first',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image_second',
            new_name='image2',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image_third',
            new_name='image3',
        ),
    ]
