# Generated by Django 3.0.5 on 2020-05-12 07:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_product_size_choose'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 5, 12, 7, 10, 58, 327469, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
